name: Deploy Lambda and Infra

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY_ACCESS }}
        aws-region: ap-south-1  # Change to your AWS region

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file C-Health-AI.yaml \
          --stack-name Cloud-Health-AI-Stack \
          --capabilities CAPABILITY_NAMED_IAM

    - name: Deploy Lambda Function (optional)
      run: |
        echo "Add your Lambda deploy step if needed"
